[project]
name = "cloudlogin"
version = "0.1.0"
description = "Cloud Login Automation"
requires-python = ">=3.10"
dependencies = [
    "boto3==1.40.1",
    "botocore==1.40.1"
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "pyright",
    "ruff"
]
